version: "3.9"
services:
  centripetal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - FILE_PATH=resources/indicators.json
